spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservice
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083